### ISSUE TITLE
Refactor the proxy target scripts to use simple `Batch`

### ISSUE THREAD

**Issue by PaulRBerg** [sablier-labs/examples#18]
Refactor the current `Batch*` contracts in the `periphery` examples to use the new simple `Batch` contract in V2 Periphery:

https://github.com/sablier-labs/v2-periphery/blob/0004fd2e61e032df3d895045ec414ecb212ddcc8/src/SablierV2Batch.sol

**Comment by andreivladbrg** [comment]
This should be done after we deploy v2.1 because we have no `SablierV2Batch` contract deployed yet

**Comment by PaulRBerg** [comment]
I will deploy it.

**Comment by PaulRBerg** [comment]
After the ENS community call, I am assigning this issue `priority0`.

I will also deploy the `Batch` contract on Mainnet now. ENS needs i.

@andreivladbrg it would be super duper helpful if you could work on this today or tomorrow! Thanks
