### ISSUE TITLE
Include flow examples

### ISSUE THREAD

**Issue by andreivladbrg** [sablier-labs/examples#36]
### Changes
- rename `v2` dir to `lockup`
- add `flow` dir
- include examples for handling streams `create` `pause` `adjust` `withdraw`
- include examples for calculations of the `rps`: e.g. X amount streamed in 3,6,12 months etc.

**Comment by smol-ninja** [comment]
Agree with all three except 1. Shouldn't we rename `v2` to `lockup` after the next lockup release?

**Comment by andreivladbrg** [comment]
> Agree with all three except 1. Shouldn't we rename `v2` to `lockup` after the next lockup release?

I think having `v2` and `flow` would be even more confusing, as people might assume that flow is v3, which we don’t want. We’ve decided on package tethering and are moving away from this approach to making releases (v1,v2 etc). wdyt?

**Comment by smol-ninja** [comment]
Good point about `v2` and `flow`. It makes sense to go with `lockup` and `flow` now.
