### ISSUE TITLE
Move StakeSablierNFT template here?

### ISSUE THREAD

**Issue by PaulRBerg** [sablier-labs/examples#39]
Why have we put the [`StakeSablierNFT`](https://github.com/sablier-labs/sablier-integration-template/blob/144e9994254fb23de8d52ac508e8040c5232717c/src/StakeSablierNFT.sol) contract in the `sablier-integration-template` repo, and not here?

**Comment by andreivladbrg** [comment]
Sounds good. I don’t remember exactly why we put it there in the beginning.

**Comment by smol-ninja** [comment]
Sounds good.
